name: ontovae
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - icu=78.2
  - ld_impl_linux-64=2.45
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - liblzma=5.8.2
  - liblzma-devel=5.8.2
  - libnsl=2.0.1
  - libsqlite=3.51.2
  - libstdcxx=15.2.0
  - libuuid=2.41.3
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.6.0
  - python=3.8.20
  - readline=8.3
  - tk=8.6.13
  - wheel=0.45.1
  - xz=5.8.2
  - xz-gpl-tools=5.8.2
  - xz-tools=5.8.2
  - zstd=1.5.7
  - pip:
      - asttokens==3.0.1
      - backcall==0.2.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - colorcet==3.1.0
      - comm==0.2.3
      - contourpy==1.1.1
      - cycler==0.12.1
      - debugpy==1.8.19
      - decorator==5.2.1
      - docopt-ng==0.9.0
      - et-xmlfile==2.0.0
      - executing==2.2.1
      - filelock==3.16.1
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - ftpretty==0.4.0
      - goatools==1.5.2
      - idna==3.11
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - ipykernel==6.29.5
      - ipython==8.12.3
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.4.2
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - kiwisolver==1.4.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mpmath==1.3.0
      - nest-asyncio==1.6.0
      - networkx==3.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - onto-vae==0.1.0
      - openpyxl==3.1.5
      - packaging==25.0
      - pandas==2.0.3
      - pandas-stubs==2.0.3.230814
      - parso==0.8.5
      - patsy==1.0.2
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.4.0
      - pip==25.0.1
      - platformdirs==4.3.6
      - prompt-toolkit==3.0.52
      - psutil==7.2.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydot==4.0.1
      - pygments==2.19.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyzmq==27.1.0
      - requests==2.32.4
      - rich==14.2.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - setuptools==75.3.3
      - six==1.17.0
      - stack-data==0.6.3
      - statsmodels==0.14.1
      - sympy==1.13.3
      - threadpoolctl==3.5.0
      - torch==2.4.1
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==3.0.0
      - types-pytz==2024.2.0.20241221
      - typing-extensions==4.13.2
      - tzdata==2025.3
      - urllib3==2.2.3
      - wcwidth==0.2.14
      - xlsxwriter==3.2.9
      - zipp==3.20.2
prefix: /home/william/miniforge3/envs/ontovae
